### ISSUE TITLE
Use properties in models.py

### ISSUE THREAD

**Issue by chrismclennon** [toms3t/Propalyzer#27]
[In models.py, it looks like you have a lot of calculated values in your Property object.](https://github.com/toms3t/Propalyzer/blob/20d1ad22ee2e3838538169dd4088620bd177809a/propalyzer_site/propalyzer_app/models.py#L80) This would make for a good use of the `@property`.

Why? Currently to retrieve `self.oper_income`, you must run `self.oper_inc_calc()` before that attribute is available, otherwise you'll receive an error that the attribute doesn't exist. That puts you in an awkward position of making sure that you've called all of your calc methods before your attributes. 

You can instead write something like:

```   
@property
def oper_income(self):
        return int(self.rent - self.vacancy)
```

When you call on the object you can just do `prop.oper_income` and it will look and act as if it were a regular attribute, while its being calculated on invocation.

I'm thinking it's a reasonably large change since you'll have to adjust where your entire codebase interacts with that object, but it should make working with your model objects a lot more sane.

**Comment by toms3t** [comment]
Great use of the @property decorator - I’m kicking myself for not thinking of using that. I’ll get testing this.


On Oct 6, 2017, at 12:14 AM, Chris McLennon <notifications@github.com<mailto:notifications@github.com>> wrote:


In models.py, it looks like you have a lot of calculated values in your Property object.<https://github.com/toms3t/Propalyzer/blob/20d1ad22ee2e3838538169dd4088620bd177809a/propalyzer_site/propalyzer_app/models.py#L80> This would make for a good use of the @property.

Why? Currently to retrieve self.oper_income, you must run self.oper_inc_calc() before that attribute is available, otherwise you'll receive an error that the attribute doesn't exist. That puts you in an awkward position of making sure that you've called all of your calc methods before your attributes.

You can instead write something like:

@property
def oper_income(self):
        return int(self.rent - self.vacancy)


When you call on the object you can just do prop.oper_income and it will look and act as if it were a regular attribute, while its being calculated on invocation.

That's a pretty big change I think, but it should make working with your model objects a lot more sane.
